/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package winrate.calculator;

import java.awt.Color;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import javax.swing.ImageIcon;

/**
 *
 * @author Keth Dominic
 */
public class AboutForm extends javax.swing.JFrame {
    int mouseX, mouseY;
    /**
     * Creates new form AboutForm
     */
    public AboutForm() {
        initComponents();
        gmailCopy();
    }
    
    public void gmailCopy(){
        this.setSize(470,338);
        gmailTP.setText("sutoroberi.coder@gmail.com");
        gmailTP.setEditable(false);
        gmailTP.setBackground(null);
        gmailTP.setBorder( null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gmailTP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usdt = new javax.swing.JLabel();
        busd = new javax.swing.JLabel();
        paypal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/winrate/calculator/pics/icons8_total_sales_25px.png")).getImage());
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("About");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("This simple program is intended to keep track");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, -1));

        jLabel2.setText("of your  win rate.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        jLabel3.setText("If you have any suggestions and comments, ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 420, -1));

        jLabel4.setText("please feel free to contact me.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 20));

        jLabel5.setText("Contact: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));

        gmailTP.setEditable(false);
        gmailTP.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        gmailTP.setText("sutoroberi.coder@gmail.com");
        gmailTP.setToolTipText("Click to copy");
        gmailTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmailTPMouseClicked(evt);
            }
        });
        gmailTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailTPActionPerformed(evt);
            }
        });
        jPanel2.add(gmailTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 270, 30));

        jLabel6.setText("Donations:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        usdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winrate/calculator/pics/usdt.png"))); // NOI18N
        usdt.setText("USDT(trc20)");
        usdt.setToolTipText("Click to copy address");
        usdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usdtMouseClicked(evt);
            }
        });
        jPanel2.add(usdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        busd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winrate/calculator/pics/Binance-USD-Crypto-Logo-PNG-Cutout (1).png"))); // NOI18N
        busd.setText("BUSD(bep20)");
        busd.setToolTipText("Click to copy address");
        busd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busdMouseClicked(evt);
            }
        });
        jPanel2.add(busd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        paypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winrate/calculator/pics/pngwing.com (1).png"))); // NOI18N
        paypal.setText("Paypal");
        paypal.setToolTipText("Click to copy paypal.me link");
        paypal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paypalMouseClicked(evt);
            }
        });
        jPanel2.add(paypal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, 240));

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 410, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gmailTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailTPActionPerformed

    private void usdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usdtMouseClicked
        // TODO add your handling code here:
        String myString = "TYfgxSmQe6YniNgBxDPyKFgHYtBV2kZU1s";
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        usdt.setForeground(Color.darkGray);
    }//GEN-LAST:event_usdtMouseClicked

    private void busdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busdMouseClicked
        // TODO add your handling code here:
        String myString = "0x42c270609cdddde24d6565c08413f075015a8d6f";
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        busd.setForeground(Color.darkGray);
    }//GEN-LAST:event_busdMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX ,y - mouseY);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void paypalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paypalMouseClicked
        // TODO add your handling code here:
        String myString = "https://paypal.me/sutorobericodes?country.x=PH&locale.x=en_US";
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        paypal.setForeground(Color.darkGray);
    }//GEN-LAST:event_paypalMouseClicked

    private void gmailTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailTPMouseClicked
        // TODO add your handling code here:
        String myString = "sutoroberi.coder@gmail.com";
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        busd.setForeground(Color.darkGray);
    }//GEN-LAST:event_gmailTPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busd;
    private javax.swing.JTextField gmailTP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paypal;
    private javax.swing.JLabel usdt;
    // End of variables declaration//GEN-END:variables
}
