/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package winrate.calculator;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Keth Dominic
 */
public class LoadFrame extends javax.swing.JFrame {

    DefaultListModel dim = new DefaultListModel();
    DefaultListModel dimWins = new DefaultListModel();
    DefaultListModel dimLoses = new DefaultListModel();
    DefaultListModel dimWR = new DefaultListModel();
    Connection con;
    /**
     * Creates new form LoadFrame
     */
    Frame main;

    public LoadFrame() throws ClassNotFoundException, SQLException {
        initComponents();
        main = new Frame();
        display();
        
    }

    public void display(){
         displayLoad();
         displayLoadWins();
         displayLoadLoses();
         displayLoadWR();
    }
    public void changeColors(){
        loadList.setSelectionBackground(Color.lightGray);
        winsList.setSelectionBackground(Color.lightGray);
        losesList.setSelectionBackground(Color.lightGray);
        wrList.setSelectionBackground(Color.lightGray);
        
        loadList.setSelectionForeground(Color.black);
        winsList.setSelectionForeground(Color.black);
        losesList.setSelectionForeground(Color.black);
        wrList.setSelectionForeground(Color.black);
        
    }
            
    public void displayLoad(){
       
        
        try {
            
            ResultSet rs;
            
            rs = main.loadData();
            
            while(rs.next()){
            dim.addElement(rs.getString("name"));
                    }
            
            loadList.setModel(dim);
            rs.close();
            

          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }
    
    
    public void displayLoadWins(){
        try {
            
            ResultSet rs;
            
            rs = main.loadDataWins();
            
            
            while(rs.next()){
            dimWins.addElement(rs.getString("wins"));
                    }
            
            winsList.setModel(dimWins);
            rs.close();
            

            
        } catch (SQLException ex) {
            Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void displayLoadLoses(){
        try {
            
            ResultSet rs;
            
            rs = main.loadDataLoses();
            
            while(rs.next()){
            dimLoses.addElement(rs.getString("loses"));
                    }
            
            losesList.setModel(dimLoses);
            rs.close();
            

            
        } catch (SQLException ex) {
            Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    public void displayLoadWR(){
        try {
            
            ResultSet rs;
            
            rs = main.loadDataWR();
            
            while(rs.next()){
            dimWR.addElement(rs.getString("win_rate"));
            
                    }
            
            wrList.setModel(dimWR);
            rs.close();
            

            
        } catch (SQLException ex) {
            Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    public String getName(){
        
        return dim.getElementAt(loadList.getSelectedIndex()).toString();
    
        
    }
    
    public void deleteData() throws ClassNotFoundException, SQLException{
        con = main.getCOnnection();
        PreparedStatement prep = con.prepareStatement("DELETE from `nameDB` WHERE `nameDB`.`name` = '"+getName()+"'");
        prep.executeUpdate();
        
    }
    
    public void deleteAllData() throws SQLException{
        con = main.getCOnnection();
        PreparedStatement prep = con.prepareStatement("DELETE from `nameDB`");
        prep.executeUpdate();
        System.out.println("All records deleted");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        loadList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        winsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        wrList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        losesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        deleteBTn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("History");
        setIconImage(new ImageIcon(getClass().getResource("/winrate/calculator/pics/icons8_total_sales_25px.png")).getImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, 400, 10));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        loadList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(loadList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        winsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(winsList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 60, 190));

        wrList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(wrList);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 60, 190));

        losesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                losesListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(losesList);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 60, 190));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));

        jLabel2.setText("Wins");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel3.setText("Loses");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel4.setText("Win Rate");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jButton1.setText("Clear History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        deleteBTn.setText("Delete");
        deleteBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBTn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loadListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadListMouseClicked
        // TODO add your handling code here:
        
        changeColors();
        winsList.setSelectedIndex(loadList.getSelectedIndex());
        losesList.setSelectedIndex(loadList.getSelectedIndex());
        wrList.setSelectedIndex(loadList.getSelectedIndex());
        
    }//GEN-LAST:event_loadListMouseClicked

    private void winsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winsListMouseClicked
        // TODO add your handling code here:
        changeColors();
        loadList.setSelectedIndex(winsList.getSelectedIndex());
        losesList.setSelectedIndex(winsList.getSelectedIndex());
        wrList.setSelectedIndex(winsList.getSelectedIndex());
    }//GEN-LAST:event_winsListMouseClicked

    private void losesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_losesListMouseClicked
        // TODO add your handling code here:
        changeColors();
        winsList.setSelectedIndex(losesList.getSelectedIndex());
        loadList.setSelectedIndex(losesList.getSelectedIndex());
        wrList.setSelectedIndex(losesList.getSelectedIndex());
    }//GEN-LAST:event_losesListMouseClicked

    private void wrListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrListMouseClicked
        // TODO add your handling code here:
        changeColors();
        winsList.setSelectedIndex(wrList.getSelectedIndex());
        losesList.setSelectedIndex(wrList.getSelectedIndex());
        loadList.setSelectedIndex(wrList.getSelectedIndex());
    }//GEN-LAST:event_wrListMouseClicked

    private void deleteBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTnActionPerformed
        // TODO add your handling code here:
        getName();
         int confirm = JOptionPane.showConfirmDialog(null, "Confirm delete this row?", "Delete row",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            try {
                deleteData();
                display();
                LoadFrame load = new LoadFrame();
                this.dispose();
                load.setVisible(true);


            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteBTnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Confirm delete all records?", "Delete all",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            try {
                deleteAllData();
                LoadFrame load = new LoadFrame();
                this.dispose();
                load.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoadFrame().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LoadFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBTn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> loadList;
    private javax.swing.JList<String> losesList;
    private javax.swing.JList<String> winsList;
    private javax.swing.JList<String> wrList;
    // End of variables declaration//GEN-END:variables
}
